// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace main_CarM8.Data
{
    public partial class Profiles
    {
        public int ProfileId { get; set; }
        public string ProfileName { get; set; }
        public string Location { get; set; }
        public DateTime DateUpdated { get; set; }
        public string Vehicle { get; set; }

        public virtual Accounts Profile { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}