// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace main_CarM8.Data
{
    public partial class Vehicles
    {
        public int VehicleId { get; set; }
        public int OwnerId { get; set; }
        public string Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string VehicleType { get; set; }
        public string Color { get; set; }
        public string Engine { get; set; }
        public int Mileage { get; set; }
        public string FuelCapacity { get; set; }

        public virtual Profiles Vehicle { get; set; }
    }
}